import { ORG_QUOTA } from "@/lib/org/tier"
import type { GateBlock, PermissionPickerBit, SettingsPageV2 } from "./types"

export const PERMISSION_PICKER: PermissionPickerBit[] = [
  {
    bit: 0,
    wire: "memory:read",
    name: "MemoryRead",
    group: "Memory",
    requires_mfa: false,
  },
  {
    bit: 1,
    wire: "memory:write",
    name: "MemoryWrite",
    group: "Memory",
    requires_mfa: false,
  },
  {
    bit: 8,
    wire: "directive:read",
    name: "DirectiveRead",
    group: "Directive",
    requires_mfa: false,
  },
  {
    bit: 9,
    wire: "directive:write",
    name: "DirectiveWrite",
    group: "Directive",
    requires_mfa: false,
  },
  {
    bit: 10,
    wire: "directive:promote",
    name: "DirectivePromote",
    group: "Directive",
    requires_mfa: true,
  },
  {
    bit: 11,
    wire: "directive:revoke",
    name: "DirectiveRevoke",
    group: "Directive",
    requires_mfa: true,
  },
  {
    bit: 16,
    wire: "session:read",
    name: "SessionRead",
    group: "Session",
    requires_mfa: false,
  },
  {
    bit: 24,
    wire: "trace:read",
    name: "TraceRead",
    group: "Trace",
    requires_mfa: false,
  },
  {
    bit: 32,
    wire: "admin:user_manage",
    name: "UserManage",
    group: "Admin",
    requires_mfa: false,
  },
  {
    bit: 33,
    wire: "admin:billing_read",
    name: "BillingRead",
    group: "Admin",
    requires_mfa: false,
  },
  {
    bit: 35,
    wire: "admin:org_settings",
    name: "OrgSettingsWrite",
    group: "Admin",
    requires_mfa: false,
  },
  {
    bit: 36,
    wire: "admin:token_create",
    name: "TokenCreate",
    group: "Admin",
    requires_mfa: false,
  },
  {
    bit: 37,
    wire: "admin:token_revoke",
    name: "TokenRevoke",
    group: "Admin",
    requires_mfa: false,
  },
  {
    bit: 49,
    wire: "admin:legal_hold",
    name: "LegalHoldManage",
    group: "Admin",
    requires_mfa: true,
  },
  {
    bit: 48,
    wire: "federation:share",
    name: "FederationShare",
    group: "Federation",
    requires_mfa: false,
  },
]

const OWNER_BITS = PERMISSION_PICKER.map((p) => p.name)

export const SETTINGS_V2: SettingsPageV2 = {
  org: ORG_QUOTA,
  settings: {
    mfa_required: false,
    // RFC 5737 TEST-NET addresses: documentation-only, never routable credentials.
    ip_allowlist: ["203.0.113.0/24", "198.51.100.0/24"],
    sso_domain: null,
    data_retention_days: 90,
    memory_extraction_enabled: true,
    drift_detection_enabled: true,
    federation_enabled: false,
  },
  embedding: {
    profile: "hosted",
    dimension: 1536,
    model_id: "text-embedding-3-small",
  },
  members: [
    {
      user_id: "usr_devon",
      name: "Devon Park",
      email: "devon@acme.com",
      role: "owner",
      status: "active",
      last_login_at: "2026-02-11T14:00:00.000Z",
      last_login_ip: "203.0.113.10",
      mfa_enabled: true,
      failed_login_attempts: 0,
      locked_until: null,
      sso_provider: null,
      sso_subject: null,
    },
    {
      user_id: "usr_sara",
      name: "Sara Chen",
      email: "sara@acme.com",
      role: "admin",
      status: "active",
      last_login_at: "2026-02-11T12:30:00.000Z",
      last_login_ip: "203.0.113.22",
      mfa_enabled: true,
      failed_login_attempts: 0,
      locked_until: null,
      sso_provider: "okta",
      sso_subject: "00u1abc",
    },
    {
      user_id: "usr_lee",
      name: "Lee Ortiz",
      email: "lee@acme.com",
      role: "member",
      status: "active",
      last_login_at: "2026-02-10T18:00:00.000Z",
      last_login_ip: "198.51.100.7",
      mfa_enabled: false,
      failed_login_attempts: 4,
      locked_until: "2026-02-11T18:00:00.000Z",
      sso_provider: null,
      sso_subject: null,
    },
    {
      user_id: "usr_inv",
      name: "Pending Invite",
      email: "new@acme.com",
      role: "viewer",
      status: "invited",
      last_login_at: null,
      last_login_ip: null,
      mfa_enabled: false,
      failed_login_attempts: 0,
      locked_until: null,
      sso_provider: null,
      sso_subject: null,
    },
  ],
  sessions: [
    {
      session_id: "sess_cur",
      device: "Chrome · Linux",
      ip: "203.0.113.10",
      last_seen_at: "2026-02-11T15:00:00.000Z",
      current: true,
    },
    {
      session_id: "sess_old",
      device: "Safari · macOS",
      ip: "198.51.100.9",
      last_seen_at: "2026-02-09T08:00:00.000Z",
      current: false,
    },
  ],
  tokens: [
    {
      token_id: "tok_91af",
      name: "Production SDK",
      prefix: "ibex_pat_0190",
      permissions: ["memory:read", "trace:read", "session:read"],
      created_at: "2026-01-15T10:00:00.000Z",
      owner_user_id: "usr_devon",
      expires_at: "2027-01-01T00:00:00.000Z",
      is_revoked: false,
      revoked_at: null,
      agent_id: null,
      allowed_ips_coming_soon: [],
    },
    {
      token_id: "tok_agent",
      name: "support-agent-bound",
      prefix: "ibex_pat_0bb2",
      permissions: ["memory:read"],
      created_at: "2026-02-01T12:00:00.000Z",
      owner_user_id: "usr_devon",
      expires_at: null,
      is_revoked: false,
      revoked_at: null,
      agent_id: "agt_01h9support",
      allowed_ips_coming_soon: [],
    },
    {
      token_id: "tok_ci",
      name: "CI Pipeline",
      prefix: "ibex_pat_88ab",
      permissions: ["session:read"],
      created_at: "2025-11-01T09:00:00.000Z",
      owner_user_id: "usr_sara",
      expires_at: "2026-01-01T00:00:00.000Z",
      is_revoked: true,
      revoked_at: "2026-01-02T00:00:00.000Z",
      agent_id: null,
      allowed_ips_coming_soon: [],
    },
  ],
  permission_picker: PERMISSION_PICKER,
  providers: [
    {
      provider_id: "prov_openai",
      provider_name: "openai",
      status: "active",
      key_hint: "****4f2a",
      base_url: null,
      last_validated_at: "2026-02-11T13:00:00.000Z",
    },
    {
      provider_id: "prov_anthropic",
      provider_name: "anthropic",
      status: "invalid",
      key_hint: "****9c1e",
      base_url: null,
      last_validated_at: "2026-02-08T18:00:00.000Z",
    },
  ],
  webhooks: [
    {
      webhook_id: "wh_01",
      url: "https://hooks.acme.com/ibex",
      events: [
        "memory.conflict_detected",
        "session.loop_detected",
        "drift.detected",
        "quota.80_percent",
      ],
      status: "active",
      secret_set: true,
      secret_hint: "whsec_…a91f",
      agent_ids: [],
      created_at: "2026-01-20T00:00:00.000Z",
    },
  ],
  legal_holds: [
    {
      hold_id: "lh_incident42",
      reason: "Incident #42 litigation hold",
      created_at: "2026-02-08T00:00:00.000Z",
      created_by: "devon@acme.com",
      active: true,
    },
  ],
  capture_policies: [
    {
      category: "prompts_completions",
      mode: "metadata_only",
      explanation:
        "metadata_only excludes raw prompts/completions from capture — only timing, token counts, and model ids.",
    },
    {
      category: "tool_args",
      mode: "metadata_only",
      explanation: "Tool names and status only; argument bodies not stored.",
    },
    {
      category: "memory_content",
      mode: "full",
      explanation: "Memory bodies retained per retention policy.",
    },
  ],
  deletion_demo_receipts: [
    { store: "postgres", status: "verified" },
    { store: "clickhouse", status: "verified" },
    { store: "redis", status: "verified" },
    { store: "object_store", status: "not_applicable" },
  ],
  audit: [
    {
      entry_id: "aud_01",
      at: "2026-02-11T14:05:00.000Z",
      actor: "devon@acme.com",
      actor_kind: "user",
      service_name: null,
      action: "token.create",
      resource_type: "token",
      resource_id: "tok_91af",
      resource_linkable: true,
      ip: "203.0.113.10",
      user_agent: "Mozilla/5.0 (X11; Linux x86_64)",
      request_id: "req_tok_create_01",
      trace_id: null,
      success: true,
      error_code: null,
      error_message: null,
      data_classification: "confidential",
      previous_state: null,
      new_state: {
        name: "Production SDK",
        permissions: ["memory:read", "trace:read"],
      },
      step_up_verified: false,
      step_up_jti: null,
      preview_token: null,
      idempotency_key: "idem_1",
      requires_second_actor: false,
      second_actor_user_id: null,
      second_actor_email: null,
      second_actor_at: null,
    },
    {
      entry_id: "aud_02",
      at: "2026-02-11T13:41:09.000Z",
      actor: "mike@acme.com",
      actor_kind: "user",
      service_name: null,
      action: "memory.bulk_export",
      resource_type: "memory",
      resource_id: "mem_772c",
      resource_linkable: true,
      ip: "198.51.100.44",
      user_agent: "curl/8.4.0",
      request_id: "req_export_772c",
      trace_id: null,
      success: false,
      error_code: "DUAL_APPROVAL_REQUIRED",
      error_message: "dual-approval required, no second actor recorded",
      data_classification: "restricted",
      previous_state: null,
      new_state: null,
      step_up_verified: true,
      step_up_jti: "jti_step_88a",
      preview_token: "pv_8f2a91c0",
      idempotency_key: "idem_x91export",
      requires_second_actor: true,
      second_actor_user_id: null,
      second_actor_email: null,
      second_actor_at: null,
    },
    {
      entry_id: "aud_03",
      at: "2026-02-11T12:02:11.000Z",
      actor: "sara@acme.com",
      actor_kind: "user",
      service_name: null,
      action: "directive.promote",
      resource_type: "directive",
      resource_id: "dir_support_refund",
      resource_linkable: true,
      ip: "203.0.113.22",
      user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X)",
      request_id: "req_promote_12",
      trace_id: "trace_a91f7c",
      success: true,
      error_code: null,
      error_message: null,
      data_classification: "restricted",
      previous_state: { version: 11, status: "draft" },
      new_state: { version: 12, status: "published" },
      step_up_verified: true,
      step_up_jti: "jti_step_12b",
      preview_token: "pv_promote_12",
      idempotency_key: "idem_promote_dir_support_v12",
      requires_second_actor: true,
      second_actor_user_id: "usr_devon",
      second_actor_email: "devon@acme.com",
      second_actor_at: "2026-02-11T12:03:40.000Z",
    },
    {
      entry_id: "aud_04",
      at: "2026-02-11T11:58:04.000Z",
      actor: "system",
      actor_kind: "service",
      service_name: "billing-enforcer",
      action: "org.suspend",
      resource_type: "organization",
      resource_id: "org_acme",
      resource_linkable: false,
      ip: "203.0.113.8",
      user_agent: null,
      request_id: "req_svc_suspend",
      trace_id: null,
      success: true,
      error_code: null,
      error_message: null,
      data_classification: "confidential",
      previous_state: { status: "active" },
      new_state: { status: "suspended", reason: "budget_hard_cap" },
      step_up_verified: false,
      step_up_jti: null,
      preview_token: null,
      idempotency_key: "idem_suspend_feb11",
      requires_second_actor: false,
      second_actor_user_id: null,
      second_actor_email: null,
      second_actor_at: null,
    },
    {
      entry_id: "aud_05",
      at: "2026-02-10T16:00:00.000Z",
      actor: "ibex_pat_0190",
      actor_kind: "token",
      service_name: null,
      action: "memory.read",
      resource_type: "memory",
      resource_id: "mem_refund_policy",
      resource_linkable: true,
      ip: "203.0.113.14",
      user_agent: "ibex-sdk/0.4.2",
      request_id: "req_mem_read_01",
      trace_id: "trace_b02e44",
      success: true,
      error_code: null,
      error_message: null,
      data_classification: "internal",
      previous_state: null,
      new_state: null,
      step_up_verified: false,
      step_up_jti: null,
      preview_token: null,
      idempotency_key: null,
      requires_second_actor: false,
      second_actor_user_id: null,
      second_actor_email: null,
      second_actor_at: null,
    },
    {
      entry_id: "aud_06",
      at: "2026-02-10T09:20:00.000Z",
      actor: "devon@acme.com",
      actor_kind: "user",
      service_name: null,
      action: "audit.export",
      resource_type: "audit_log",
      resource_id: "export_batch_02",
      resource_linkable: false,
      ip: "203.0.113.10",
      user_agent: "Mozilla/5.0",
      request_id: "req_audit_export",
      trace_id: null,
      success: true,
      error_code: null,
      error_message: null,
      data_classification: "confidential",
      previous_state: null,
      new_state: { format: "csv", rows: 412 },
      step_up_verified: false,
      step_up_jti: null,
      preview_token: null,
      idempotency_key: "idem_audit_export_02",
      requires_second_actor: false,
      second_actor_user_id: null,
      second_actor_email: null,
      second_actor_at: null,
    },
    {
      entry_id: "aud_07",
      at: "2026-02-09T18:12:00.000Z",
      actor: "sara@acme.com",
      actor_kind: "user",
      service_name: null,
      action: "legal_hold.place",
      resource_type: "legal_hold",
      resource_id: "lh_incident42",
      resource_linkable: false,
      ip: "203.0.113.22",
      user_agent: "Mozilla/5.0",
      request_id: "req_hold_42",
      trace_id: null,
      success: true,
      error_code: null,
      error_message: null,
      data_classification: "restricted",
      previous_state: null,
      new_state: { reason: "Incident #42 litigation hold", active: true },
      step_up_verified: true,
      step_up_jti: "jti_hold_49",
      preview_token: "pv_hold_42",
      idempotency_key: "idem_hold_42",
      requires_second_actor: false,
      second_actor_user_id: null,
      second_actor_email: null,
      second_actor_at: null,
    },
  ],
  caller: {
    role: "owner",
    bits: OWNER_BITS,
    feature_flags: {
      IBEX_AUTH_TOTP_ENABLED: true,
      legal_hold_ui: true,
    },
    kill_switches: { operator_mutations: false },
    step_up_active: false,
    step_up_expires_at: null,
  },
  residual_ch_ttl_under_hold: true,
}

export function evaluateGate(
  caller: SettingsPageV2["caller"],
  opts: {
    featureFlag?: string
    killSwitch?: string
    bit?: string
    requiresStepUp?: boolean
    tierFeature?: { allowed: boolean; name: string }
  },
): GateBlock {
  if (opts.featureFlag && !caller.feature_flags[opts.featureFlag]) {
    return { kind: "feature_flag", flag: opts.featureFlag }
  }
  if (opts.killSwitch && caller.kill_switches[opts.killSwitch]) {
    return { kind: "kill_switch", switch: opts.killSwitch }
  }
  if (opts.tierFeature && !opts.tierFeature.allowed) {
    return { kind: "tier", feature: opts.tierFeature.name }
  }
  if (opts.bit && !caller.bits.includes(opts.bit)) {
    return { kind: "permission", bit: opts.bit }
  }
  if (opts.requiresStepUp && !caller.step_up_active) {
    return { kind: "step_up" }
  }
  return null
}

export function gateMessage(block: GateBlock): string {
  if (!block) return ""
  if (block.kind === "feature_flag") return `Feature flag off: ${block.flag}`
  if (block.kind === "kill_switch") return `Kill-switch: ${block.switch}`
  if (block.kind === "permission") return `Missing permission: ${block.bit}`
  if (block.kind === "tier")
    return `Tier does not include ${block.feature} — upgrade`
  return "Step-up required"
}

export const WEBHOOK_EVENTS = [
  {
    domain: "Memory",
    events: ["memory.created", "memory.conflict_detected"],
  },
  {
    domain: "Session",
    events: ["session.failed", "session.loop_detected"],
  },
  {
    domain: "Drift",
    events: ["drift.detected"],
  },
  {
    domain: "Directive",
    events: ["directive.promoted", "directive.revoked"],
  },
  {
    domain: "Quota",
    events: ["quota.80_percent", "quota.95_percent", "quota.exceeded"],
  },
]

/** Catalog of BYO LLM providers — not configured until a credential exists. */
export const PROVIDER_CATALOG = [
  { id: "openai", label: "OpenAI" },
  { id: "anthropic", label: "Anthropic" },
  { id: "google", label: "Google" },
  { id: "azure", label: "Azure OpenAI" },
] as const
