version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 5
  labels:
  - dependencies
  - github-actions
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 5
  labels:
  - dependencies
  - go
- package-ecosystem: gomod
  directory: /.github/tools/licenses
  schedule:
    interval: monthly
  open-pull-requests-limit: 1
  labels:
  - dependencies
  - go
  - ci-tools
  ignore:
  - dependency-name: gopkg.in/src-d/go-git.v4
- package-ecosystem: docker
  directory: /services/auth
  schedule:
    interval: daily
  labels:
  - dependencies
  - docker
- package-ecosystem: docker
  directory: /services/proxy
  schedule:
    interval: daily
  labels:
  - dependencies
  - docker
- package-ecosystem: npm
  directory: /
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 5
  labels:
  - dependencies
  - area/web
