coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
  ignore:
    - "packages/proto/gen/go/**"
  flags:
    go:
      paths:
        - packages/
        - services/
    embedder:
      paths:
        - services/embedder/app/
    context:
      paths:
        - services/context/app/
