import type {
  AgentConfig,
  AgentDetail,
  AgentListItem,
  AgentStatus,
} from "./types"

const defaultConfig = (partial?: Partial<AgentConfig>): AgentConfig => ({
  memory_extraction_enabled: true,
  memory_scope: "agent",
  max_memories_per_context: 12,
  context_budget_tokens: 8000,
  drift_detection_enabled: true,
  drift_sensitivity: 0.35,
  loop_detection_threshold: 3,
  heartbeat_interval_seconds: 30,
  llm_providers: ["openai", "anthropic"],
  default_provider: "openai",
  default_model: "gpt-4-turbo",
  ...partial,
})

function listFields(d: AgentDetail): AgentListItem {
  const {
    agent_id,
    name,
    slug,
    description,
    status,
    tags,
    total_sessions,
    total_memories,
    total_tokens_used,
    last_active_at,
    active_directive_version_id,
    active_directive_version,
    active_directive_hash,
    default_provider,
    default_model,
    created_at,
    updated_at,
  } = d
  return {
    agent_id,
    name,
    slug,
    description,
    status,
    tags,
    total_sessions,
    total_memories,
    total_tokens_used,
    last_active_at,
    active_directive_version_id,
    active_directive_version,
    active_directive_hash,
    default_provider,
    default_model,
    created_at,
    updated_at,
  }
}

/** In-memory store — mutates like the real API for UI wiring demos. */
export const AGENT_STORE: AgentDetail[] = [
  {
    agent_id: "agt_01h9support",
    org_id: "org_acme",
    name: "Support Agent",
    slug: "support-agent",
    description: "Enterprise refund and escalation handling",
    status: "active",
    tags: ["prod", "customer-facing"],
    total_sessions: 1842,
    total_memories: 9402,
    total_tokens_used: 45_200_000,
    last_active_at: "2026-02-11T14:20:00.000Z",
    active_directive_version_id: "dv_support_v3",
    active_directive_version: 3,
    active_directive_hash: "9f2a",
    default_provider: "openai",
    default_model: "gpt-4-turbo",
    created_at: "2025-06-01T10:00:00.000Z",
    updated_at: "2026-02-11T14:20:00.000Z",
    active_session_count: 14,
    config: defaultConfig(),
  },
  {
    agent_id: "agent_billing",
    org_id: "org_acme",
    name: "billing-bot",
    slug: "billing-bot",
    description: "Quote and discount conversations",
    status: "paused",
    tags: ["prod", "billing"],
    total_sessions: 620,
    total_memories: 2104,
    total_tokens_used: 8_400_000,
    last_active_at: "2026-02-11T12:00:00.000Z",
    active_directive_version_id: "dv_billing_v4",
    active_directive_version: 4,
    active_directive_hash: "aa11",
    default_provider: "openai",
    default_model: "gpt-4-turbo",
    created_at: "2025-07-12T10:00:00.000Z",
    updated_at: "2026-02-10T18:00:00.000Z",
    active_session_count: 0,
    config: defaultConfig({
      memory_scope: "org",
      drift_detection_enabled: false,
      default_model: "gpt-4-turbo",
    }),
  },
  {
    agent_id: "agt_01h9docs",
    org_id: "org_acme",
    name: "docs-helper",
    slug: "docs-helper",
    description: "Documentation Q&A over product manuals",
    status: "active",
    tags: ["prod", "internal"],
    total_sessions: 410,
    total_memories: 1800,
    total_tokens_used: 3_100_000,
    last_active_at: "2026-02-11T14:10:00.000Z",
    active_directive_version_id: "dv_docs_v8",
    active_directive_version: 8,
    active_directive_hash: "4e88",
    default_provider: "anthropic",
    default_model: "claude-3-opus",
    created_at: "2025-08-01T10:00:00.000Z",
    updated_at: "2026-02-11T14:10:00.000Z",
    active_session_count: 3,
    config: defaultConfig({
      llm_providers: ["anthropic", "openai"],
      default_provider: "anthropic",
      default_model: "claude-3-opus",
      context_budget_tokens: 12000,
    }),
  },
  {
    agent_id: "agt_01h9triage",
    org_id: "org_acme",
    name: "triage",
    slug: "triage",
    description: "Inbound ticket classification",
    status: "suspended",
    tags: ["ops"],
    total_sessions: 88,
    total_memories: 220,
    total_tokens_used: 410_000,
    last_active_at: "2026-01-20T09:00:00.000Z",
    active_directive_version_id: null,
    active_directive_version: null,
    active_directive_hash: null,
    default_provider: null,
    default_model: null,
    created_at: "2025-09-01T10:00:00.000Z",
    updated_at: "2026-01-20T09:00:00.000Z",
    active_session_count: 0,
    config: defaultConfig({
      memory_extraction_enabled: false,
      default_provider: null,
      default_model: null,
      llm_providers: ["openai"],
    }),
  },
  {
    agent_id: "agt_01h9sched",
    org_id: "org_acme",
    name: "scheduler",
    slug: "scheduler",
    description: "Meeting and reminder orchestration",
    status: "archived",
    tags: ["legacy"],
    total_sessions: 1204,
    total_memories: 500,
    total_tokens_used: 1_900_000,
    last_active_at: "2025-11-01T09:00:00.000Z",
    active_directive_version_id: "dv_sched_v2",
    active_directive_version: 2,
    active_directive_hash: "1a0c",
    default_provider: "openai",
    default_model: "gpt-3.5-turbo",
    created_at: "2025-05-01T10:00:00.000Z",
    updated_at: "2025-11-02T09:00:00.000Z",
    active_session_count: 0,
    config: defaultConfig({
      default_model: "gpt-3.5-turbo",
      drift_detection_enabled: false,
    }),
  },
  {
    agent_id: "agt_01h9onboard",
    org_id: "org_acme",
    name: "onboarding",
    slug: "onboarding",
    description: "New customer welcome flows",
    status: "active",
    tags: ["prod", "growth"],
    total_sessions: 0,
    total_memories: 0,
    total_tokens_used: 0,
    last_active_at: null,
    active_directive_version_id: null,
    active_directive_version: null,
    active_directive_hash: null,
    default_provider: "openai",
    default_model: "gpt-4-turbo",
    created_at: "2026-02-01T10:00:00.000Z",
    updated_at: "2026-02-01T10:00:00.000Z",
    active_session_count: 0,
    config: defaultConfig({ max_memories_per_context: 6 }),
  },
  ...Array.from({ length: 14 }, (_, n) => {
    const status = (["active", "paused", "suspended", "archived"] as const)[
      n % 4
    ]
    return {
      agent_id: `agt_gen_${String(n + 10).padStart(2, "0")}`,
      org_id: "org_acme",
      name: `helper-${n + 10}`,
      slug: `helper-${n + 10}`,
      description: `Synthetic agent ${n + 10} for list density`,
      status: status as AgentStatus,
      tags: n % 2 === 0 ? ["prod"] : ["staging"],
      total_sessions: (n * 41) % 2000,
      total_memories: (n * 17) % 5000,
      total_tokens_used: ((n + 1) * 250_000) % 20_000_000,
      last_active_at:
        n % 5 === 0
          ? null
          : `2026-02-${String((n % 10) + 1).padStart(2, "0")}T12:00:00.000Z`,
      active_directive_version_id: n % 3 === 0 ? null : `dv_gen_${n}`,
      active_directive_version: n % 3 === 0 ? null : (n % 6) + 1,
      active_directive_hash: n % 3 === 0 ? null : `h${n}`,
      default_provider:
        n % 4 === 0 ? null : n % 2 === 0 ? "openai" : "anthropic",
      default_model:
        n % 4 === 0 ? null : n % 2 === 0 ? "gpt-4-turbo" : "claude-3-opus",
      created_at: "2025-10-01T10:00:00.000Z",
      updated_at: "2026-02-01T10:00:00.000Z",
      active_session_count: status === "active" ? n % 5 : 0,
      config: defaultConfig({
        default_provider:
          n % 4 === 0 ? null : n % 2 === 0 ? "openai" : "anthropic",
        default_model:
          n % 4 === 0 ? null : n % 2 === 0 ? "gpt-4-turbo" : "claude-3-opus",
      }),
    } satisfies AgentDetail
  }),
]

export function toListItem(d: AgentDetail): AgentListItem {
  return listFields(d)
}

export const ALL_TAGS = Array.from(
  new Set(AGENT_STORE.flatMap((a) => a.tags)),
).sort()
