import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Blocks,
  BookMarked,
  BookOpen,
  Boxes,
  Brain,
  Circle,
  CircleHelp,
  Container,
  Database,
  FileCode,
  FileText,
  Flag,
  Gauge,
  GitBranch,
  GitCompareArrows,
  History,
  Key,
  Layers,
  LayoutDashboard,
  Lightbulb,
  Lock,
  Map,
  Plug,
  Rocket,
  Scale,
  ScrollText,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  Target,
  Terminal,
  Users,
  Waypoints,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Lucide export name → component */
export const LUCIDE_BY_NAME: Record<string, LucideIcon> = {
  Activity,
  AlertCircle,
  AlertTriangle,
  Blocks,
  BookMarked,
  BookOpen,
  Boxes,
  Brain,
  Circle,
  CircleHelp,
  Container,
  Database,
  FileCode,
  FileText,
  Flag,
  Gauge,
  GitBranch,
  GitCompareArrows,
  History,
  Key,
  Layers,
  LayoutDashboard,
  Lightbulb,
  Lock,
  Map,
  Plug,
  Rocket,
  Scale,
  ScrollText,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  Target,
  Terminal,
  Users,
  Waypoints,
  Zap,
};

/** Docs section folders in meta.json */
export const SECTION_ICONS: Record<string, LucideIcon> = {
  "getting-started": Rocket,
  architecture: Boxes,
  proxy: Waypoints,
  auth: Shield,
  security: ShieldCheck,
  deployment: Container,
  operations: Activity,
  "api-reference": Terminal,
  adr: ScrollText,
  changelog: History,
  glossary: BookMarked,
};

/** Full doc paths (without /docs/) */
export const PAGE_ICONS: Record<string, LucideIcon> = {
  "getting-started/introduction": BookOpen,
  "getting-started/quickstart": Zap,
  "getting-started/concepts": Lightbulb,
  "getting-started/faq": CircleHelp,
  "architecture/overview": LayoutDashboard,
  "architecture/services": Boxes,
  "architecture/data-model": Database,
  "architecture/request-lifecycle": GitBranch,
  "proxy/overview": LayoutDashboard,
  "proxy/configuration": Settings,
  "proxy/authentication": Lock,
  "proxy/auth-caching": Gauge,
  "proxy/directives": FileText,
  "proxy/sessions": Layers,
  "proxy/rate-limiting": Gauge,
  "proxy/request-routing": GitBranch,
  "proxy/provider-adapters": Plug,
  "auth/overview": Shield,
  "auth/issuing-api-keys": Key,
  "auth/org-project-model": Users,
  "auth/multi-tenant-rls": Database,
  "security/overview": ShieldCheck,
  "security/authentication": Lock,
  "security/tenant-isolation": Database,
  "security/secrets-and-keys": Key,
  "deployment/docker-compose": Container,
  "deployment/kubernetes": Boxes,
  "deployment/environment-variables": Settings,
  "operations/observability": Activity,
  "operations/traces-and-clickhouse": Database,
  "operations/troubleshooting": CircleHelp,
  "operations/health-checks": Gauge,
  "operations/incident-response": AlertCircle,
  "api-reference/auth-grpc": Terminal,
  "api-reference/http-routes": GitBranch,
  "api-reference/proxy-health": Activity,
  "api-reference/chat-completions": Plug,
  "api-reference/errors": AlertCircle,
  "adr/index": ScrollText,
  glossary: BookMarked,
  changelog: ScrollText,
};

/** Leaf slug fallbacks when path is ambiguous */
export const SLUG_ICONS: Record<string, LucideIcon> = {
  overview: LayoutDashboard,
  configuration: Settings,
  authentication: Lock,
  introduction: BookOpen,
  quickstart: Zap,
  concepts: Lightbulb,
  faq: CircleHelp,
  services: Boxes,
  "data-model": Database,
  "request-lifecycle": GitBranch,
  "tenant-isolation": Database,
  "secrets-and-keys": Key,
  observability: Activity,
  troubleshooting: CircleHelp,
  "health-checks": Gauge,
  "incident-response": AlertCircle,
  "auth-grpc": Terminal,
  "proxy-health": Activity,
  "chat-completions": Plug,
  errors: AlertCircle,
  goals: Target,
  decisions: Scale,
  risks: AlertTriangle,
  milestones: Flag,
  "current-state": Activity,
  findings: AlertCircle,
  "content-sources": ScrollText,
  "master-brief": ScrollText,
};

/** Roadmap top-level phase folders */
export const ROADMAP_PHASE_ICONS: Record<string, LucideIcon> = {
  "phase-0-foundation": Map,
  "phase-1-core-platform": Layers,
  "phase-1-5-docs-site": BookOpen,
  "phase-2-single-provider": Plug,
  "phase-2-5-provider-generalization": Blocks,
  "phase-3-memory-engine": Lightbulb,
  "phase-3-5-extraction-assembly": GitBranch,
  "phase-4-multi-provider": Waypoints,
  "phase-4-5-intelligence-layer": Brain,
  "phase-5-advanced-retrieval": Search,
  reference: BookMarked,
};

/** Roadmap nested section folders */
export const ROADMAP_SECTION_ICONS: Record<string, LucideIcon> = {
  milestones: Flag,
  reference: BookOpen,
  goals: Target,
  tracks: GitBranch,
  decisions: Scale,
  risks: AlertTriangle,
};

/** Full roadmap paths (without /roadmap/) */
export const ROADMAP_PAGE_ICONS: Record<string, LucideIcon> = {
  overview: LayoutDashboard,
  "current-state": Activity,
  findings: AlertCircle,
  "reference/index": BookMarked,
  "phase-0-foundation/index": Map,
  "phase-1-core-platform/index": Layers,
  "phase-1-5-docs-site/index": BookOpen,
  "phase-2-single-provider/index": Plug,
  "phase-2-5-provider-generalization/index": Blocks,
  "phase-3-memory-engine/index": Lightbulb,
  "phase-3-5-extraction-assembly/index": GitBranch,
  "phase-4-multi-provider/index": Waypoints,
  "phase-4-5-intelligence-layer/index": Brain,
  "phase-5-advanced-retrieval/index": Search,
  "phase-1-5-docs-site/goals": Target,
  "phase-1-5-docs-site/decisions": Scale,
  "phase-1-5-docs-site/risks": AlertTriangle,
  "phase-1-5-docs-site/content-sources": ScrollText,
  "phase-1-5-docs-site/master-brief": ScrollText,
  "phase-1-5-docs-site/phase-1-5-docs-site-milestones": Flag,
};

/** Benchmark dashboard sidebar pages */
export const BENCHMARK_PAGE_ICONS: Record<string, LucideIcon> = {
  "/benchmarks": LayoutDashboard,
  "/benchmarks/latency": Activity,
  "/benchmarks/waterfall": Layers,
  "/benchmarks/load": Zap,
  "/benchmarks/history": History,
  "/benchmarks/compare": GitCompareArrows,
  "/benchmarks/memory": Brain,
  "/benchmarks/memory/latency": Activity,
  "/benchmarks/memory/history": History,
  "/benchmarks/memory/compare": GitCompareArrows,
};
