"""Generated mounted route policy rows; regenerate with services/api/scripts/generate_route_policy.py."""

from __future__ import annotations

from typing import Final

ORGANIZATIONS_ROUTER_SOURCE: Final = 'services/api/app/routers/organizations.py'
PROVIDERS_ROUTER_SOURCE: Final = 'services/api/app/routers/providers.py'
ROUTE_PATH_V1_AGENTS_AGENT_ID: Final = '/v1/agents/{agent_id}'
ROUTE_PATH_V1_ORGANIZATIONS_ORG_ID: Final = '/v1/organizations/{org_id}'
ROUTE_PATH_V1_ORGANIZATIONS_ORG_ID_MODEL_POLICIES_POLICY_ID: Final = '/v1/organizations/{org_id}/model-policies/{policy_id}'
ROUTE_PATH_V1_USERS_USER_ID: Final = '/v1/users/{user_id}'

ROUTE_POLICY: Final[tuple[dict[str, object], ...]] = (
    {'method': 'GET', 'path': '/docs', 'auth_source': 'public', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'default', 'evidence': 'inventory_only', 'endpoint': 'fastapi.applications.FastAPI.setup.<locals>.swagger_ui_html', 'source': None},
    {'method': 'GET', 'path': '/docs/oauth2-redirect', 'auth_source': 'public', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'default', 'evidence': 'inventory_only', 'endpoint': 'fastapi.applications.FastAPI.setup.<locals>.swagger_ui_redirect', 'source': None},
    {'method': 'GET', 'path': '/health', 'auth_source': 'public', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'default', 'evidence': 'inventory_only', 'endpoint': 'app.probes.health', 'source': None},
    {'method': 'GET', 'path': '/metrics', 'auth_source': 'public', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'default', 'evidence': 'inventory_only', 'endpoint': 'app.probes.metrics', 'source': None},
    {'method': 'GET', 'path': '/openapi.json', 'auth_source': 'public', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'default', 'evidence': 'inventory_only', 'endpoint': 'fastapi.applications.FastAPI.setup.<locals>.openapi', 'source': None},
    {'method': 'GET', 'path': '/ready', 'auth_source': 'public', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'default', 'evidence': 'inventory_only', 'endpoint': 'app.probes.ready', 'source': None},
    {'method': 'GET', 'path': '/redoc', 'auth_source': 'public', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'default', 'evidence': 'inventory_only', 'endpoint': 'fastapi.applications.FastAPI.setup.<locals>.redoc_html', 'source': None},
    {'method': 'GET', 'path': '/v1/agents', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.agents.list_agents', 'source': None},
    {'method': 'POST', 'path': '/v1/agents', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.agents.create_agent', 'source': None},
    {'method': 'DELETE', 'path': ROUTE_PATH_V1_AGENTS_AGENT_ID, 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.agents.delete_agent', 'source': None},
    {'method': 'GET', 'path': ROUTE_PATH_V1_AGENTS_AGENT_ID, 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.agents.get_agent', 'source': None},
    {'method': 'PATCH', 'path': ROUTE_PATH_V1_AGENTS_AGENT_ID, 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.agents.patch_agent', 'source': None},
    {'method': 'POST', 'path': '/v1/agents/{agent_id}/activate', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.agents.activate_agent', 'source': None},
    {'method': 'POST', 'path': '/v1/agents/{agent_id}/archive', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.agents.archive_agent', 'source': None},
    {'method': 'POST', 'path': '/v1/agents/{agent_id}/pause', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.agents.pause_agent', 'source': None},
    {'method': 'GET', 'path': '/v1/operator/context', 'auth_source': 'operator_session', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.operator_overview.operator_context', 'source': None},
    {'method': 'GET', 'path': '/v1/operator/events/stream', 'auth_source': 'operator_permission', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.operator_events.stream_events', 'source': None},
    {'method': 'GET', 'path': '/v1/operator/overview', 'auth_source': 'operator_session', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.operator_overview.operator_overview', 'source': None},
    {'method': 'GET', 'path': '/v1/operator/platform/health', 'auth_source': 'operator_permission', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.platform.platform_health', 'source': None},
    {'method': 'POST', 'path': '/v1/operator/session/login', 'auth_source': 'pat_exchange', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.session.login', 'source': None},
    {'method': 'POST', 'path': '/v1/operator/session/logout', 'auth_source': 'operator_session', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': True, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.session.logout', 'source': None},
    {'method': 'GET', 'path': '/v1/operator/session/me', 'auth_source': 'operator_session', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.session.me', 'source': None},
    {'method': 'POST', 'path': '/v1/operator/session/refresh', 'auth_source': 'operator_session', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': True, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.session.refresh_session', 'source': None},
    {'method': 'GET', 'path': '/v1/operator/traces', 'auth_source': 'operator_session', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.operator_traces.operator_trace_list', 'source': None},
    {'method': 'GET', 'path': '/v1/operator/traces/{trace_id}', 'auth_source': 'operator_session', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.operator_traces.operator_trace_detail', 'source': None},
    {'method': 'DELETE', 'path': ROUTE_PATH_V1_ORGANIZATIONS_ORG_ID, 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.organizations.delete_org', 'source': None},
    {'method': 'GET', 'path': ROUTE_PATH_V1_ORGANIZATIONS_ORG_ID, 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.organizations.get_org', 'source': None},
    {'method': 'PATCH', 'path': ROUTE_PATH_V1_ORGANIZATIONS_ORG_ID, 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.organizations.patch_org', 'source': None},
    {'method': 'GET', 'path': '/v1/organizations/{org_id}/budget-periods', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.billing.list_budget_periods', 'source': None},
    {'method': 'POST', 'path': '/v1/organizations/{org_id}/budget-periods', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.billing.create_budget_period', 'source': None},
    {'method': 'GET', 'path': '/v1/organizations/{org_id}/capture-policies', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.capture_policies.list_capture_policies', 'source': None},
    {'method': 'POST', 'path': '/v1/organizations/{org_id}/capture-policies', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.capture_policies.create_capture_policy', 'source': None},
    {'method': 'GET', 'path': '/v1/organizations/{org_id}/capture-policies/resolved', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.capture_policies.resolve_capture_mode', 'source': None},
    {'method': 'DELETE', 'path': '/v1/organizations/{org_id}/capture-policies/{policy_id}', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.capture_policies.delete_capture_policy', 'source': None},
    {'method': 'PATCH', 'path': '/v1/organizations/{org_id}/capture-policies/{policy_id}', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.capture_policies.patch_capture_policy', 'source': None},
    {'method': 'GET', 'path': '/v1/organizations/{org_id}/deletion-jobs/{job_id}', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.organizations.get_org_deletion_job', 'source': None},
    {'method': 'GET', 'path': '/v1/organizations/{org_id}/legal-holds', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.legal_holds.list_holds', 'source': None},
    {'method': 'POST', 'path': '/v1/organizations/{org_id}/legal-holds', 'auth_source': 'operator_session', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': True, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.legal_holds.set_hold', 'source': None},
    {'method': 'POST', 'path': '/v1/organizations/{org_id}/legal-holds/{hold_id}/clear', 'auth_source': 'operator_session', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': True, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.legal_holds.clear_hold', 'source': None},
    {'method': 'GET', 'path': '/v1/organizations/{org_id}/model-policies', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.model_policies.list_model_policies', 'source': None},
    {'method': 'POST', 'path': '/v1/organizations/{org_id}/model-policies', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.model_policies.create_model_policy', 'source': None},
    {'method': 'DELETE', 'path': ROUTE_PATH_V1_ORGANIZATIONS_ORG_ID_MODEL_POLICIES_POLICY_ID, 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.model_policies.delete_model_policy', 'source': None},
    {'method': 'GET', 'path': ROUTE_PATH_V1_ORGANIZATIONS_ORG_ID_MODEL_POLICIES_POLICY_ID, 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.model_policies.get_model_policy', 'source': None},
    {'method': 'PATCH', 'path': ROUTE_PATH_V1_ORGANIZATIONS_ORG_ID_MODEL_POLICIES_POLICY_ID, 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.model_policies.patch_model_policy', 'source': None},
    {'method': 'GET', 'path': '/v1/organizations/{org_id}/providers', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.providers.list_providers', 'source': None},
    {'method': 'POST', 'path': '/v1/organizations/{org_id}/providers', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.providers.upsert_provider', 'source': None},
    {'method': 'DELETE', 'path': '/v1/organizations/{org_id}/providers/{provider_name}', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.providers.delete_provider', 'source': None},
    {'method': 'GET', 'path': '/v1/organizations/{org_id}/rate-cards', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.billing.list_rate_cards', 'source': None},
    {'method': 'POST', 'path': '/v1/organizations/{org_id}/rate-cards', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.billing.create_rate_card', 'source': None},
    {'method': 'POST', 'path': '/v1/organizations/{org_id}/rate-cards/{card_id}/versions', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.billing.publish_rate_card_version', 'source': None},
    {'method': 'GET', 'path': '/v1/organizations/{org_id}/rate-limits', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.rate_limits.get_rate_limits', 'source': None},
    {'method': 'PATCH', 'path': '/v1/organizations/{org_id}/rate-limits', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.rate_limits.patch_rate_limits', 'source': None},
    {'method': 'POST', 'path': '/v1/organizations/{org_id}/suspend', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.organizations.suspend_org', 'source': None},
    {'method': 'POST', 'path': '/v1/organizations/{org_id}/usage/query', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.usage_query.query_usage', 'source': None},
    {'method': 'GET', 'path': '/v1/tenant/ping', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.tenant.tenant_ping', 'source': None},
    {'method': 'GET', 'path': '/v1/tokens', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.tokens.list_tokens', 'source': None},
    {'method': 'POST', 'path': '/v1/tokens', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.tokens.create_token', 'source': None},
    {'method': 'DELETE', 'path': '/v1/tokens/{token_id}', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.tokens.delete_token', 'source': None},
    {'method': 'GET', 'path': '/v1/tokens/{token_id}', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.tokens.get_token', 'source': None},
    {'method': 'GET', 'path': '/v1/users', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.users.list_users', 'source': None},
    {'method': 'POST', 'path': '/v1/users', 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.users.create_user', 'source': None},
    {'method': 'DELETE', 'path': ROUTE_PATH_V1_USERS_USER_ID, 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.users.delete_user', 'source': None},
    {'method': 'GET', 'path': ROUTE_PATH_V1_USERS_USER_ID, 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.users.get_user', 'source': None},
    {'method': 'PATCH', 'path': ROUTE_PATH_V1_USERS_USER_ID, 'auth_source': 'bearer_pat', 'role': 'explicit_route_dependency', 'permission': 'declared_by_endpoint_dependency', 'organization_source': 'verified_token_or_session', 'action': None, 'anti_enumeration': 'route_dependency_contract', 'unavailable_result': '503_without_side_effect', 'csrf_origin_required': False, 'cache_control': 'no-store', 'evidence': 'inventory_only', 'endpoint': 'app.routers.users.patch_user', 'source': None},
)


def policy_keys() -> frozenset[tuple[str, str]]:
    return frozenset((str(row['method']), str(row['path'])) for row in ROUTE_POLICY)
