"""Canonical IBEX error code strings (UPPER_SNAKE_CASE)."""

from __future__ import annotations

MISSING_TOKEN = "MISSING_TOKEN"
INVALID_TOKEN = "INVALID_TOKEN"
INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"
VALIDATION_ERROR = "VALIDATION_ERROR"
NOT_FOUND = "NOT_FOUND"
INTERNAL_ERROR = "INTERNAL_ERROR"
SERVICE_DEGRADED = "SERVICE_DEGRADED"
AUTH_UNAVAILABLE = "AUTH_UNAVAILABLE"
