"""Permission bits — must match packages/permissions (ADR-0009)."""

from __future__ import annotations

MEMORY_READ = 1 << 0
MEMORY_WRITE = 1 << 1
MEMORY_DELETE = 1 << 2
MEMORY_BULK_EXPORT = 1 << 3
DIRECTIVE_READ = 1 << 8
DIRECTIVE_WRITE = 1 << 9
DIRECTIVE_PROMOTE = 1 << 10
DIRECTIVE_REVOKE = 1 << 11
SESSION_CREATE = 1 << 16
SESSION_READ = 1 << 17
SESSION_TERMINATE = 1 << 18
OPERATOR_METADATA_READ = 1 << 19
TRACE_READ = 1 << 24
TRACE_EXPORT = 1 << 25
USER_MANAGE = 1 << 32
BILLING_READ = 1 << 33
BILLING_MANAGE = 1 << 34
ORG_SETTINGS_WRITE = 1 << 35
TOKEN_CREATE = 1 << 36
TOKEN_REVOKE = 1 << 37
OPERATOR_REDACTED_READ = 1 << 38
OPERATOR_RAW_READ = 1 << 39
MARKETPLACE_PUBLISH = 1 << 40
MARKETPLACE_INSTALL = 1 << 41
OPERATOR_EXPORT = 1 << 42
OPERATOR_DELETE = 1 << 43
OPERATOR_REPLAY = 1 << 44
SECRET_USE = 1 << 45
POLICY_CHANGE = 1 << 46
BREAK_GLASS = 1 << 47
FEDERATION_SHARE = 1 << 48

AGENT_DEFAULT = MEMORY_READ | MEMORY_WRITE | SESSION_CREATE | SESSION_READ | TRACE_READ
PROXY_CHAT_COMPLETION = MEMORY_READ | SESSION_CREATE | SESSION_READ | SECRET_USE
READ_ONLY = MEMORY_READ | DIRECTIVE_READ | SESSION_READ | TRACE_READ
ADMIN = (
    AGENT_DEFAULT
    | DIRECTIVE_READ
    | DIRECTIVE_WRITE
    | DIRECTIVE_PROMOTE
    | DIRECTIVE_REVOKE
    | SESSION_TERMINATE
    | TRACE_EXPORT
    | USER_MANAGE
    | BILLING_READ
    | BILLING_MANAGE
    | ORG_SETTINGS_WRITE
    | TOKEN_CREATE
    | TOKEN_REVOKE
)

VIEWER_OPERATOR_DEFAULT = OPERATOR_METADATA_READ | OPERATOR_REDACTED_READ
MEMBER_OPERATOR_DEFAULT = VIEWER_OPERATOR_DEFAULT
ADMIN_OPERATOR_DEFAULT = MEMBER_OPERATOR_DEFAULT | OPERATOR_EXPORT | POLICY_CHANGE

_STEP_UP_MASK = (
    DIRECTIVE_PROMOTE
    | DIRECTIVE_REVOKE
    | OPERATOR_RAW_READ
    | OPERATOR_EXPORT
    | OPERATOR_DELETE
    | OPERATOR_REPLAY
    | SECRET_USE
    | POLICY_CHANGE
    | BREAK_GLASS
)

ROLE_BITMAP = {
    "owner": ADMIN | ADMIN_OPERATOR_DEFAULT,
    "admin": ADMIN | ADMIN_OPERATOR_DEFAULT,
    "member": AGENT_DEFAULT | MEMBER_OPERATOR_DEFAULT,
    "viewer": READ_ONLY | VIEWER_OPERATOR_DEFAULT,
}


def has_permission(bitmap: int, required: int) -> bool:
    return bitmap & required == required


def bitmap_for_role(role: str) -> int:
    return ROLE_BITMAP.get(role, 0)


def requires_step_up(permission: int) -> bool:
    return permission & _STEP_UP_MASK != 0


def requires_mfa(permission: int) -> bool:
    return requires_step_up(permission)
